// app/(front-end)/(public)/layout.tsx

import type { Metadata } from "next";
import Navbar from "@/app/ui/shared/navbar/navbar";
import Footer from "@/app/ui/shared/foooter/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}