import type { Metadata } from "next";
import Navbar from "../ui/shared/navbar/navbar";
import Footer from "../ui/shared/foooter/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}